site_name: Docs
theme: readthedocs

pages:
- Home: index.md
- Chapter 1 Title:
    - 'Chapter 1': 'chapter1/intro.md'
- Chapter 2 Title:
    - 'Chapter 2 Only': 'chapter2/chapter-2.md'
    - 'Intro Chapter 2': 'chapter2/intro.md'
